[package]
name = "graph_slide_puzzle"
version = "0.1.0"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.9.11"
pathfinding = "2.0.3"
serde = { version= "1.0.104", features = ["derive"] }
serde_json = "1.0.44"